### ISSUE TITLE
Issue at Creating ISO image

### ISSUE THREAD

**Issue by 10lalib** [ntdevlabs/tiny11builder#36] opened 2023-03-22 10:48 UTC
Hello, after running all steps as administrator around the end part of the process i get this error and the iso file is not created. Please help fix this issue.
"""""
Creating ISO image...
'C:\Users\Mech' is not recognized as an internal or external command,
operable program or batch file.
Creation completed Press any key to exit the script...
Press any key to continue . . .
"""""

Thank you

**Comment by codyalank** [comment] 2023-04-13 05:30
Ran into the same problem, ended up coping the extracted folder into by C drive (not sure if this actually made a difference), and renamed the folder to "tiny". Path is now "C:\tiny\tiny". Ran it again and it worked. Hope this helps.

**Comment by Uleepera** [comment] 2023-04-23 14:22
I can also verify moving to c: fixes the issue.

**Comment by jazzman1825** [comment] 2023-04-30 12:07
As described in the [similar issue](https://github.com/ntdevlabs/tiny11builder/issues/39). The problem is spaces in the path. Just make sure there are no spaces in the path to the bat file.

**Closed** 2024-05-01 14:25 UTC
