### ISSUE TITLE
Tiny10 Builder Please

### ISSUE THREAD

**Issue by nikkdrive18** [ntdevlabs/tiny11builder#113] opened 2023-10-21 02:42 UTC
Hi, I still prefer using Win10 over Win11, but i want to use Win-10-PRO as source instead of Enterprise to make Tiny10.
Can You please make a Tiny10 Builder which I can Use To make Tiny10pro.

BONUS : Since Microsoft has stopped releasing new versions this will most likely not need to be updated.

**Comment by daboynb** [comment] 2023-10-31 00:46
I made a script based on this awesome project that supports win10 too.

https://github.com/daboynb/windows_scripts/tree/main/windows_custom_iso_maker

**Comment by Darthagnon** [comment] 2024-04-26 18:15
I would love to have a Tiny10 builder, to produce lite versions of older releases of Win10 for VMs and testing.

PS. Looks like this issue is a duplicate of #80

**Closed** 2024-05-01 20:29 UTC

**Comment by nikkdrive18** [comment] 2024-05-02 17:18
> I made a script based on this awesome project that supports win10 too.
> 
> https://github.com/daboynb/windows_scripts/tree/main/windows_custom_iso_maker

Thanks I will try it.

**Comment by itsmengwh08** [comment] 2025-09-13 01:36
> I made a script based on this awesome project that supports win10 too.
> 
> https://github.com/daboynb/windows_scripts/tree/main/windows_custom_iso_maker

I don't recommend trying his work. It sucks
